services:
  - type: web
    name: portfolio-admin
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: BACKEND_URL
        value: https://portfolio-backend-ro4m.onrender.com
      - key: VITE_BASE_PATH
        value: /
      - key: VITE_BACKEND_URL
        value: https://portfolio-backend-ro4m.onrender.com
